### ISSUE TITLE
complilation error in ubuntu 18.04

### ISSUE THREAD

**Issue by zhouzhiqian** [sybrenstuvel/Python-RVO2#19]
Hello, I meet a compilation error in ubuntu 18.04. and I hope someone could help me. 

At first, I get a similar error with https://github.com/sybrenstuvel/Python-RVO2/issues/15. 
And I try to delete the empty build directory. Later, I meet another similar error.

running build
running build_ext
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:34 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/nubot117/workspace/Python-RVO2/build/RVO2/CMakeFiles/CMakeOutput.log".
See also "/home/nubot117/workspace/Python-RVO2/build/RVO2/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/home/nubot117/anaconda3/envs/rgl/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/nubot117/anaconda3/envs/rgl/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/nubot117/anaconda3/envs/rgl/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/nubot117/anaconda3/envs/rgl/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/nubot117/anaconda3/envs/rgl/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/nubot117/anaconda3/envs/rgl/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 19, in run
    cwd=build_dir)
  File "/home/nubot117/anaconda3/envs/rgl/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '../..', '-DCMAKE_CXX_FLAGS=-fPIC']' returned non-zero exit status 1.

**Comment by zhouzhiqian** [comment]
After I realized the key point is that **No CMAKE_CXX_COMPILER could be found.**  I easily found a solution as shown below:
_sudo apt-get update
sudo apt-get install -y build-essential_

Thanks SUNGBEOMCHOI for the helpful issue https://github.com/sybrenstuvel/Python-RVO2/issues/15 .
