### ISSUE TITLE
subprocess.CalledProcessError: Command '['cmake', '../..', '-DCMAKE_CXX_FLAGS=-fPIC']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Monceeeeeeeeeeeeef** [sybrenstuvel/Python-RVO2#24]
running build
running build_ext
CMake Deprecation Warning at CMakeLists.txt:33 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/moncef/trajnet++/trajnetplusplusdataset/Python-RVO2-master/build/RVO2/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/home/moncef/trajnet++/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 19, in run
    cwd=build_dir)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '../..', '-DCMAKE_CXX_FLAGS=-fPIC']' returned non-zero exit status 1.

why this error is happening ?

**Comment by adamsigal** [comment]
Did you figure out  how to fix this?

**Comment by Yuanzizizi** [comment]
How to solve it? I got the same problem ...

**Comment by adamsigal** [comment]
I believe it worked once I specified `Cython==0.21.1` in `requirements.txt`. I'm also using a python 3.6 venv.
