### ISSUE TITLE
build error in ubuntu 20.04

### ISSUE THREAD

**Issue by sumitmishra209** [sybrenstuvel/Python-RVO2#29]
Firstly, cynton new version is installing but the version mentioned in requirement can't. After that executing "python setup.py build" is creating below error. Any suggestion will be helpful.  

running build
running build_ext
No such file or directory
CMake Error: Generator: execution of make failed. Make command was:  -f Makefile && 
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/home/sumit/trajnet++/trajnetv/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 20, in run
    subprocess.check_call(['cmake', '--build', '.'], cwd=build_dir)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 1.

**Comment by Yuanzizizi** [comment]
python setup.py build_ext --inplace
running build_ext
Error: could not load cache
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/home/xxx/.conda/envs/env_RVO2/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/xxx/.conda/envs/env_RVO2/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/xxx/.conda/envs/env_RVO2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 20, in run
    subprocess.check_call(['cmake', '--build', '.'], cwd=build_dir)
  File "/home/xxx/.conda/envs/env_RVO2/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 1.

I got a similar problem, any suggestion?

**Comment by hjl-12** [comment]
ubuntu 18.04
I got a similar problem.
Have you solve it?

**Comment by dfloegel** [comment]
I had the same error and could resolve it with installing: 
python -m pip install cmake 
python -m pip install Cython 
leading to versions cmake==3.25.2 and Cython==0.29.33 

afterwards I could use 
python setup.py build
python setup.py install

I am using python 3.8

**Comment by m29w** [comment]
Hi I am unable to run these commands in python 3.11.4.


> python setup.py build_ext --inplace running build_ext Error: could not load cache Traceback (most recent call last): File "setup.py", line 49, in 'Topic :: Software Development :: Libraries :: Python Modules', File "/home/xxx/.conda/envs/env_RVO2/lib/python3.6/distutils/core.py", line 148, in setup dist.run_commands() File "/home/xxx/.conda/envs/env_RVO2/lib/python3.6/distutils/dist.py", line 955, in run_commands self.run_command(cmd) File "/home/xxx/.conda/envs/env_RVO2/lib/python3.6/distutils/dist.py", line 974, in run_command cmd_obj.run() File "setup.py", line 20, in run subprocess.check_call(['cmake', '--build', '.'], cwd=build_dir) File "/home/xxx/.conda/envs/env_RVO2/lib/python3.6/subprocess.py", line 291, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 1.
> 
> I got a similar problem, any suggestion?

Same error

**Comment by DanielFloegel** [comment]
I succesfully installed the library in python 3.11.6 with  cmake==3.25.2 and Cython==0.29.33
However I was running on Ubuntu 22.04

I could solve some issues by installing all the extras of Python 3.11 in Step3 of: https://www.linuxcapable.com/how-to-install-python-3-11-on-ubuntu-linux/ . In particular the dev mode was necesary.

**Comment by guchi-ac** [comment]
thank you DanielFloegel
