### ISSUE TITLE
subprocess.CalledProcessError: Command '['cmake', '../..', '-DCMAKE_CXX_FLAGS=-fPIC']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Yuanzizizi** [sybrenstuvel/Python-RVO2#30]
python setup.py build

^[[A
running build
running build_ext
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- Check for working C compiler: /cm/shared/apps/gcc8/8.4.0/bin/gcc
-- Check for working C compiler: /cm/shared/apps/gcc8/8.4.0/bin/gcc -- broken
CMake Error at /cm/shared/apps/cmake/3.5.1/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/cm/shared/apps/gcc8/8.4.0/bin/gcc" is not able to compile
  a simple test program.

  It fails with the following output:

   Change Dir: /home/xxx/CrowdNav-master/Python-RVO2-main/build/RVO2/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/gmake" "cmTC_302d1/fast"

  /usr/bin/gmake -f CMakeFiles/cmTC_302d1.dir/build.make
  CMakeFiles/cmTC_302d1.dir/build

  gmake[1]: Entering directory
  `/home/xxx/CrowdNav-master/Python-RVO2-main/build/RVO2/CMakeFiles/CMakeTmp'

  Building C object CMakeFiles/cmTC_302d1.dir/testCCompiler.c.o

  /cm/shared/apps/gcc8/8.4.0/bin/gcc -o
  CMakeFiles/cmTC_302d1.dir/testCCompiler.c.o -c
  /home/xxx/CrowdNav-master/Python-RVO2-main/build/RVO2/CMakeFiles/CMakeTmp/testCCompiler.c

  Linking C executable cmTC_302d1

  /cm/shared/apps/cmake/3.5.1/bin/cmake -E cmake_link_script
  CMakeFiles/cmTC_302d1.dir/link.txt --verbose=1

  /cm/shared/apps/gcc8/8.4.0/bin/gcc
  CMakeFiles/cmTC_302d1.dir/testCCompiler.c.o -o cmTC_302d1 -rdynamic

  /usr/bin/ld: cannot find crt1.o: No such file or directory

  /usr/bin/ld: cannot find crti.o: No such file or directory

  collect2: error: ld returned 1 exit status

  gmake[1]: *** [cmTC_302d1] Error 1

  gmake[1]: Leaving directory
  `/home/xxx/CrowdNav-master/Python-RVO2-main/build/RVO2/CMakeFiles/CMakeTmp'

  gmake: *** [cmTC_302d1/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:34 (project)

-- Configuring incomplete, errors occurred!
See also "/home/xxx/CrowdNav-master/Python-RVO2-main/build/RVO2/CMakeFiles/CMakeOutput.log".
See also "/home/xxx/CrowdNav-master/Python-RVO2-main/build/RVO2/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/home/xxx/.conda/envs/env_RVO2/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/xxx/.conda/envs/env_RVO2/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/xxx/.conda/envs/env_RVO2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/xxx/.conda/envs/env_RVO2/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/xxx/.conda/envs/env_RVO2/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/xxx/.conda/envs/env_RVO2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 19, in run
    cwd=build_dir)
  File "/home/xxx/.conda/envs/env_RVO2/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '../..', '-DCMAKE_CXX_FLAGS=-fPIC']' returned non-zero exit status 1.

Any advice?

**Comment by Mokchanic** [comment]
Erase the build folder inside the Python-RVO2 and try rebuilding it.
