### ISSUE TITLE
Unable to build on either Ubuntu or Windows system

### ISSUE THREAD

**Issue by TheAdityaKedia** [sybrenstuvel/Python-RVO2#6]
I have both Cmake and Cython (recommended version) installed. However, when I execute the command 

`python setup.py build`

I get the following error

`running build
running build_ext
Error: could not load cache
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 20, in run
    subprocess.check_call(['cmake', '--build', '.'], cwd=build_dir)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 1.`

I am wondering what the issue is and how it can be fixed.

**Comment by sybrenstuvel** [comment]
`cd` to the RVO build directory and run `cmake --build .`; by running it yourself you should get more info than just "it failed".

**Comment by TheAdityaKedia** [comment]
Did that. Got the following error

`Error: could not load cache`

**Comment by sybrenstuvel** [comment]
It should produce more output -- please give all of it.

**Comment by TheAdityaKedia** [comment]
Hi, when I ran the command from `cmake --build` on a windows system, that is the only output I got. I re did the entire process with a new clone however, and now can somehow install the package on both Ubuntu and Windows.
However, while I can import the library in Ubuntu, `import rvo2' on windows gives the following output 

`Traceback (most recent call last):`
`      File "<stdin>", line 1, in <module>`
`ModuleNotFoundError: No module named 'rvo2'`

**Comment by sybrenstuvel** [comment]
That's for you to debug, as these kind of issues are very computer-dependent. Check where the files ended up, and whether Python can find them (check what's in your `sys.path` list).

**Comment by TheAdityaKedia** [comment]
I understand. Thanks a bunch for your help!

**Comment by Saleh-Gholam-Zadeh** [comment]
Hello 
I have same issue and I couldn't solve it.

I have both Cmake and Cython (recommended version) installed. However, when I execute the command

`python` setup.py build`
I get the following error

`Error: could not load cache
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/home/saleh/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/home/saleh/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/saleh/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/saleh/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/saleh/anaconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/saleh/anaconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/saleh/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/saleh/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/saleh/anaconda3/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/saleh/anaconda3/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/home/saleh/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/saleh/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/saleh/anaconda3/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/saleh/anaconda3/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/saleh/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/saleh/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 20, in run
    subprocess.check_call(['cmake', '--build', '.'], cwd=build_dir)
  File "/home/saleh/anaconda3/lib/python3.7/subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 1.
`

and when I ran `cmake --build .` in the build directory I only received `Error: could not load cache
`

**Comment by pepeleduin** [comment]
Please, take time to check [this fork](https://github.com/ktk1501/Python-RVO2). I successfully install and get data.
